FROM eclipse-temurin:11-jdk-focal
 

 
WORKDIR /Users/mpratapcisco.com/Downloads/java
#RUN chmod 777 /Users/mpratapcisco.com/downloads/java
#RUN chmod 777 /Users/mpratapcisco.com/Documents/Test1/docker-spring-boot/target
 
#COPY ./target/docker-spring-boot-0.0.1-SNAPSHOT.jar /Users/mpratapcisco.com/Downloads/java
#COPY /Users/mpratapcisco.com/Documents/Test1/docker-spring-boot/target/docker-spring-boot-0.0.1-SNAPSHOT.jar /Users/mpratapcisco.com/Downloads/java

EXPOSE 8080

 
CMD ["java", "-jar", "docker-spring-boot-0.0.1-SNAPSHOT.jar"]